# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=15000"]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "develop"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: bump-build-version
        name: Auto increment build number
        description: Increments the build part of the version by 1 on every commit using tbump
        entry: .venv/bin/python scripts/bump_build.py
        language: system
        always_run: true
        pass_filenames: false
#  - repo: https://github.com/pycqa/pydocstyle
#    rev: 6.3.0
#    hooks:
#      - id: pydocstyle
