name: Docker Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]
  workflow_run:
    workflows: ["Bump Minor Version on PR Merge"]
    types: [completed]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    # Only run on workflow_run if the bump workflow succeeded
    if: |
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success' ||
      github.event_name != 'workflow_run'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Note: GITHUB_TOKEN is automatically available for ghcr.io
      # No explicit login needed when using GITHUB_TOKEN

      - name: Debug GitHub context
        run: |
            echo "Repository: ${{ github.repository }}"
            echo "Owner: ${{ github.repository_owner }}"
            echo "Actor: ${{ github.actor }}"
            echo "Ref: ${{ github.ref_name }}"
            echo "VERSION: ${{ steps.version.outputs.version }}"

      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: test
          push: false
          tags: |
            app:test-${{ steps.version.outputs.version }}
            app:test-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build production image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: ${{ github.event_name == 'workflow_run' }}
          platforms: linux/amd64,linux/arm64
          tags: |
            app:${{ steps.version.outputs.version }}
            app:production-latest
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
